name: Deploy

on:
  push:
    branches:
      - master
      
  schedule:
    - cron: '0 * * * *'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🧪 Build and deploy
        uses: victoriadrake/jekyll-cd@master
      - uses: actions/checkout@master
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        env:
          USER: root
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
