name: Deploy to Workers Staging

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install Jekyll
        run: |
          sudo gem install bundler jekyll
          sudo bundle install

      - name: Install Wrangler
        run: sudo npm i @cloudflare/wrangler -g

      - name: Build
        run: bundle exec jekyll build

      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        env:
          USER: root
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
